import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { site, categories, topics, faqs } from './content.mjs';
import { generateCovers } from './covers.mjs';
import { alertsBody, dealsBody, resourcesBody, radarDesk, radarDeskV2, radarDeskV3, alertsBodyV2 } from './extra-content.mjs';

const out = path.resolve('dist');
fs.rmSync(out,{recursive:true,force:true});
fs.mkdirSync(path.join(out,'articles'),{recursive:true});
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
fs.copyFileSync('styles.css',path.join(out,'assets','styles.css'));
fs.copyFileSync('cover-styles.css',path.join(out,'assets','cover-styles.css'));
fs.copyFileSync('tech-theme.css',path.join(out,'assets','tech-theme.css'));
fs.copyFileSync('extra-pages.css',path.join(out,'assets','extra-pages.css'));
fs.copyFileSync('hero-refresh.css',path.join(out,'assets','hero-refresh.css'));
fs.copyFileSync('hero-v2.css',path.join(out,'assets','hero-v2.css'));
fs.copyFileSync('radar-fix.css',path.join(out,'assets','radar-fix.css'));
fs.copyFileSync('background-tech.css',path.join(out,'assets','background-tech.css'));
fs.copyFileSync('background-pro.css',path.join(out,'assets','background-pro.css'));
fs.copyFileSync('radar-background-motion.css',path.join(out,'assets','radar-background-motion.css'));
fs.copyFileSync('favicon.svg',path.join(out,'assets','favicon.svg'));
fs.cpSync(path.resolve('assets','recommendations'),path.join(out,'assets','recommendations'),{recursive:true});
fs.mkdirSync(path.resolve('assets'),{recursive:true});
fs.copyFileSync('styles.css',path.resolve('assets','styles.css'));
fs.copyFileSync('cover-styles.css',path.resolve('assets','cover-styles.css'));
fs.copyFileSync('tech-theme.css',path.resolve('assets','tech-theme.css'));
fs.copyFileSync('extra-pages.css',path.resolve('assets','extra-pages.css'));
fs.copyFileSync('hero-refresh.css',path.resolve('assets','hero-refresh.css'));
fs.copyFileSync('hero-v2.css',path.resolve('assets','hero-v2.css'));
fs.copyFileSync('radar-fix.css',path.resolve('assets','radar-fix.css'));
fs.copyFileSync('background-tech.css',path.resolve('assets','background-tech.css'));
fs.copyFileSync('background-pro.css',path.resolve('assets','background-pro.css'));
fs.copyFileSync('radar-background-motion.css',path.resolve('assets','radar-background-motion.css'));
fs.copyFileSync('favicon.svg',path.resolve('assets','favicon.svg'));
generateCovers({topics,categories,destinations:[out,path.resolve('.')]});

const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const url=p=>site.url+(p==='/'?'':p);
const nav=`<header class="top"><div class="nav wrap"><a class="brand" href="/index.html"><span class="radar"><i></i></span><b>机场雷达</b></a><nav aria-label="主导航"><a href="/index.html">首页</a><a href="/topics/recommend.html">机场推荐</a><a href="/topics/shadowrocket.html">小火箭</a><a href="/topics/security.html">知识与安全</a><a href="/topics/test.html">测评方法</a><a href="/topics/client.html">客户端教程</a><a href="/articles/index.html">全部文章</a><a href="/faq.html">FAQ</a><a href="/about.html">关于</a></nav><button class="menu" aria-label="打开菜单">☰</button></div></header>`;
const footer=`<footer><div class="wrap footer-grid"><div><a class="brand light" href="/index.html"><span class="radar"><i></i></span><b>机场雷达</b></a><p>${site.tagline}</p></div><div><b>浏览</b><a href="/articles/index.html">全部文章</a><a href="/faq.html">常见问题</a><a href="/about.html">编辑原则</a></div><div><b>提醒</b><p>本站不提供节点或代购服务。请遵守所在地法律与服务条款。</p></div></div><div class="wrap legal">© 2026 机场雷达 · 内容仅供一般信息参考</div></footer>`;
function layout({title,desc,pathName='/',body,schema='',type='website'}){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="shortcut icon" href="/assets/favicon.svg"><link rel="canonical" href="${url(pathName)}"><meta property="og:type" content="${type}"><meta property="og:site_name" content="${site.name}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${url(pathName)}"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/styles.css"><link rel="alternate" type="application/rss+xml" title="机场雷达 RSS" href="/rss.xml"><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"WebSite",name:site.name,url:site.url,description:site.description,inLanguage:'zh-CN'})}</script>${schema}</head><body>${nav}<main>${body}</main>${footer}<script>document.querySelector('.menu').onclick=()=>document.querySelector('header nav').classList.toggle('open')</script></body></html>`}
const articlePartners=[
  {name:'闪电鼠',code:'sd88',logo:'shandianshu.jpg',url:'https://chaore01.shandianshuaff.com/#/?code=HeUwm3zo',line:'轻量入门到大流量档位均有覆盖'},
  {name:'大佬云',code:'dly88',logo:'dalaoyun.png',url:'https://chaore01.dalaoyunaff.com/#/?code=rtH3pPer',line:'月付、年付与一次性流量灵活搭配'},
  {name:'神行加速',code:'sx0077',logo:'shenxing.png',url:'https://chaore01.shenxingaff.com/#/?code=iTjS2mVY',line:'流量档位清晰，适合持续使用需求'},
  {name:'云界线',code:'yjx888',logo:'yunjiexian.png',url:'https://chaore01.yunjiexianaff.com/#/?code=g2PDAa91',line:'常规月付与备用流量方案兼顾'},
  {name:'榴莲云',code:'ll88',logo:'liulianyun.png',url:'https://chaore01.liulianyunaff.com/#/?code=MNqUefcg',line:'提供面向多设备用户的大流量档位'},
  {name:'环球梯',code:'HQ66',logo:'huanqiuti.jpg',url:'https://chaore01.huanqiutiaff.com/#/?code=vXn9xcb8',line:'从学生轻量档到一次性流量均有选择'}
];
const write=(p,s)=>{
  const depth=p.split('/').length-1;
  const prefix='../'.repeat(depth);
  let enhanced=s;
  if(p.startsWith('articles/')&&p!=='articles/index.html'){
    const articleIndex=topics.findIndex(article=>p===`articles/${article.slug}.html`);
    const partnerIndex=((articleIndex<0?0:articleIndex)*5+2)%articlePartners.length;
    const partner=articlePartners[partnerIndex];
    const partnerCard=`<aside class="article-partner"><img src="/assets/recommendations/${partner.logo}" alt="${partner.name} Logo" loading="lazy" width="96" height="96"><div><small>本文合作推荐</small><h2>${partner.name}</h2><p>${partner.line}。结算时输入优惠码 <b>${partner.code}</b>，活动规则以推荐页说明为准。</p></div><a href="/topics/recommend.html#provider-${partnerIndex+1}">查看推荐套餐 →</a></aside>`;
    enhanced=enhanced.replace('</article>',partnerCard+'</article>');
  }
  enhanced=enhanced.replace('<a href="/topics/recommend.html">机场推荐</a>','<a href="/topics/recommend.html">机场推荐</a><a href="/deals.html">机场优惠码</a><a class="nav-alert" href="/alerts.html">跑路预警</a>');
  enhanced=enhanced.replace('<a href="/about.html">关于</a>','<a href="/resources.html">资源栏</a><a href="/about.html">关于</a>');
  enhanced=enhanced.replace(/<strong>\d{2}<\/strong>/g,'');
  if(p==='index.html') enhanced=enhanced.replace('<section class="hero">','<section class="hero"><div class="ambient-radar" aria-hidden="true"><span class="ring r1"></span><span class="ring r2"></span><span class="ring r3"></span><span class="axis-x"></span><span class="axis-y"></span><i class="sweep"></i><i class="blip b1"></i><i class="blip b2"></i><i class="blip b3"></i><i class="blip b4"></i><small class="bearing north">000°</small><small class="bearing east">090°</small><small class="bearing south">180°</small><small class="bearing west">270°</small></div>');
  if(p==='topics/shadowrocket.html') enhanced=enhanced.replace('<section class="section wrap">','<section class="download-hub wrap"><div class="download-head"><span>OFFICIAL DOWNLOADS</span><h2>客户端官方下载</h2><p>只使用官方商店或项目发布页，避免第三方重打包、植入广告或篡改版本。</p></div><div class="download-grid"><article class="download-card"><div class="download-icon rocket-mark">↗</div><div><small>iPhone / iPad / Mac</small><h3>Shadowrocket 小火箭</h3><p>Apple App Store 官方版本。软件本身不包含节点或订阅服务。</p><a href="https://apps.apple.com/us/app/shadowrocket/id932747118" target="_blank" rel="noopener noreferrer nofollow">前往 App Store 官方下载 →</a></div></article><article class="download-card"><div class="download-icon clash-mark">◇</div><div><small>Windows / macOS / Linux</small><h3>Clash Verge Rev</h3><p>项目目前通过 GitHub Releases 发布，请根据系统和处理器架构选择安装包。</p><a href="https://github.com/clash-verge-rev/clash-verge-rev/releases" target="_blank" rel="noopener noreferrer nofollow">前往 GitHub 官方发布页 →</a></div></article></div><div class="download-warning"><b>安全提示</b><span>不要下载所谓“内置节点版”“永久免费破解版”，也不要向陌生安装包授予证书、VPN 或管理员权限。</span></div></section><section class="section wrap">');
  if(p==='deals.html'){
    const registrations={sd88:'https://chaore01.shandianshuaff.com/#/?code=HeUwm3zo',dly88:'https://chaore01.dalaoyunaff.com/#/?code=rtH3pPer',sx0077:'https://chaore01.shenxingaff.com/#/?code=iTjS2mVY',yjx888:'https://chaore01.yunjiexianaff.com/#/?code=g2PDAa91',ll88:'https://chaore01.liulianyunaff.com/#/?code=MNqUefcg',HQ66:'https://chaore01.huanqiutiaff.com/#/?code=vXn9xcb8'};
    for(const [code,href] of Object.entries(registrations)) enhanced=enhanced.replace(`data-code="${code}">复制优惠码</button>`,`data-code="${code}">复制优惠码</button><a class="coupon-register" href="${href}" target="_blank" rel="noopener noreferrer nofollow sponsored">前往官网注册 →</a>`);
  }
  if(p==='topics/recommend.html') enhanced=enhanced.replaceAll('新增四家','另外四家').replace('新增推荐入口','更多老牌入口').replace('以下服务目前仅展示注册入口','以下老牌服务目前仅展示注册入口');
  if(p==='about.html') enhanced=enhanced.replace('</main>','<section class="legal-contact"><div class="wrap legal-contact-grid"><div class="disclaimer-panel"><span>DISCLAIMER</span><h2>免责声明</h2><p>本站内容仅用于一般网络知识、软件使用与隐私安全教育，不构成法律、投资或购买建议。本站不提供、不销售、不代购任何节点、订阅或翻墙服务，也不保证第三方软件、服务或外部链接永久可用、绝对安全或适用于所有地区。</p><p>读者应自行了解并遵守所在地法律法规、单位网络政策和第三方平台条款。因使用本站信息、下载第三方软件、访问外部链接或自行配置网络工具产生的任何直接或间接损失，由使用者自行承担。外部项目的功能、价格、隐私政策与安全性由其开发者负责。</p><p>本站会尽力核对信息，但软件版本、项目地址和政策可能随时变化。如发现内容失效或存在安全问题，请通过下方 Telegram 联系。</p></div><aside class="contact-panel"><span>CONTACT</span><h2>联系机场雷达</h2><p>内容勘误、失效链接、安全提醒与合作咨询。</p><a class="tg-button" href="https://t.me/ace668811" target="_blank" rel="noopener noreferrer" aria-label="通过 Telegram 联系机场雷达">点击联系 Telegram →</a><small>请勿发送订阅链接、密码、验证码或其他敏感信息。</small></aside></div></section></main>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/cover-styles.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/tech-theme.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/extra-pages.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/hero-refresh.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/hero-v2.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/radar-fix.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/background-tech.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/background-pro.css"></head>');
  if(p.endsWith('.html')) enhanced=enhanced.replace('</head>','<link rel="stylesheet" href="/assets/radar-background-motion.css"></head>');
  if(p==='index.html') enhanced=enhanced.replace(/<div class="hero-art">.*?<\/div><\/div><\/section>(?=<section class="ticker">)/s,radarDeskV3.replace('{{ARTICLE_COUNT}}',String(topics.length))+'</div></section>');
  if(p.startsWith('articles/')&&p!=='articles/index.html'){
    const slug=path.basename(p,'.html');
    enhanced=enhanced.replace('<div class="takeaway">',`<figure class="article-cover"><img src="/assets/covers/${slug}.svg" alt="文章主题封面" width="1200" height="630"></figure><div class="takeaway">`);
  }
  const portable=p.endsWith('.html')
    ? enhanced.replace(/((?:href|src)=")\/([^"]*)/g,(_,attr,target)=>`${attr}${target?prefix+target:(prefix||'./')}`)
    : enhanced;
  const f=path.join(out,p);
  fs.mkdirSync(path.dirname(f),{recursive:true});
  fs.writeFileSync(f,portable);
  const mirror=path.resolve(p);
  fs.mkdirSync(path.dirname(mirror),{recursive:true});
  fs.writeFileSync(mirror,portable);
};
function card(a){return `<article class="card"><a class="card-top c-${a.category}" href="/articles/${a.slug}.html"><img src="/assets/covers/${a.slug}.svg" alt="${esc(a.title)}文章封面" loading="lazy" width="1200" height="630"><span>${categories[a.category].name}</span><strong>${String(topics.indexOf(a)+1).padStart(2,'0')}</strong></a><div class="card-body"><div class="meta">${a.date} · ${a.read} 分钟阅读</div><h3><a href="/articles/${a.slug}.html">${a.title}</a></h3><p>${a.dek}</p><a class="read" href="/articles/${a.slug}.html">继续阅读 <span>→</span></a></div></article>`}
const homeBody=`<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">INDEPENDENT NETWORK FIELD NOTES</div><h1>网络工具不该<br>靠玄学来选。</h1><p>${site.description}</p><div class="actions"><a class="btn primary" href="/articles/vpn-jichang-guide.html">从新手指南开始</a><a class="btn ghost" href="/articles/shadowrocket-complete-guide.html">查看小火箭教程</a></div><div class="trust"><span>✓ 不卖节点</span><span>✓ 不接软文</span><span>✓ 先讲风险</span></div></div><div class="hero-art"><div class="scan"></div><div class="orb"><span>${topics.length}</span><small>实用指南</small></div><div class="signal s1"></div><div class="signal s2"></div><div class="float f1">晚高峰稳定性</div><div class="float f2">订阅安全</div><div class="float f3">规则分流</div></div></div></section><section class="ticker"><div>SHADOWROCKET <i>•</i> CLASH <i>•</i> 隐私安全 <i>•</i> 节点测速 <i>•</i> 新手避坑 <i>•</i> SHADOWROCKET</div></section><section class="section wrap"><div class="section-head"><div><span>本周精选</span><h2>先解决最常见的问题</h2></div><a href="/articles/index.html">全部文章 →</a></div><div class="featured">${topics.slice(0,3).map(card).join('')}</div></section><section class="dark"><div class="wrap principles"><div><span class="kicker">我们的判断方式</span><h2>不做“最快最好”的空口推荐</h2></div><div class="principle-list"><div><b>01</b><h3>连续观察</h3><p>一次测速只是快照。我们更看晚高峰、丢包和故障恢复。</p></div><div><b>02</b><h3>明确边界</h3><p>工具能做什么、不能做什么，以及使用前该知道的隐私代价。</p></div><div><b>03</b><h3>可复现步骤</h3><p>每个排错结论都拆成普通人能逐项验证的检查点。</p></div></div></div></section><section class="section wrap"><div class="section-head"><div><span>最新更新</span><h2>刚整理好的实用笔记</h2></div></div><div class="grid">${topics.slice(3,9).map(card).join('')}</div></section><section class="newsletter"><div class="wrap"><div><span>RADAR BRIEF</span><h2>少一点营销，多一点判断依据。</h2><p>收藏本站，遇到连接、测速和客户端问题时回来查。</p></div><a class="btn lightbtn" href="/faq.html">先看常见问题</a></div></section>`;
write('index.html',layout({title:'机场雷达｜VPN 机场、小火箭与代理工具实用指南',desc:site.description,body:homeBody}));

const headings=['先把概念说清楚','实际使用时怎么判断','一套不会越查越乱的步骤','容易踩的坑','我们的建议'];
const expand=(a,i)=>[
`很多教程一上来就让人复制链接、切换参数，却没有说明为什么。关于“${a.title.replace(/：.*/,'')}”，真正值得先弄清的是使用目标：你是偶尔浏览网页、长期远程工作、观看视频，还是只想解决某个应用的连接问题？目标不同，判断标准也不同。${a.points[0]} 先把这个边界定下来，后面的每一步才有意义。`,
`${a.points[1]} 实际操作中，建议把设备、本地网络、客户端、订阅和节点看成一条链。任何一环出错，表面上都可能表现为“连不上”或“很慢”。最省时间的方法不是同时改五个设置，而是从本地网络开始，一层一层验证，并给每次变化留下记录。`,
`${a.points[2]} 我们习惯用对照法：关闭工具测试一次，打开后用默认配置测试一次，再只更换节点测试一次。三组结果足以排除大量干扰。若要联系客服，请提供时间、设备系统、网络运营商、节点名称和错误日志；不要提供完整订阅链接、密码或含令牌的截图。`,
`${a.points[3]} 还有一个常见误区，是把宣传词当作技术结论。所谓“专线”“原生”“不限速”只有在测试条件、使用限制和持续表现都能说明时才有参考价值。节点数量也并非越多越好：几十个无人维护的入口，通常不如几个状态透明、故障能及时恢复的入口。`,
`如果你刚开始使用，先保留默认设置，完成最小可用配置，再考虑规则、DNS 或脚本。每增加一层自定义，就多一个潜在故障点。截图保存原始参数，更新前备份，确认来源，能避免大部分“改完再也回不去”的情况。`,
`隐私方面也要保持现实预期。网络工具可以改变部分流量的出口和路径，但不会让账号、Cookie、设备指纹或你主动填写的信息消失。不要安装来历不明的定制客户端，不要随意导入根证书，不要把敏感订阅交给在线转换服务。系统更新、强密码与双重验证依然是基础。`,
`速度测试最好固定变量。使用同一台设备、同一个 Wi‑Fi、同一个测速目标，分别记录延迟、抖动、丢包和持续下载速度。至少覆盖白天与晚高峰。一次跑分很好看，只能说明那一分钟的情况；连续几天都能用，才接近日常体验。`,
`当结果不符合预期时，先问“是所有网站都失败，还是只有一个？”“换蜂窝网络是否正常？”“其他设备是否复现？”这三个问题可以快速区分目标站、本地网络和服务端故障。不要把浏览器缓存、账号地区限制或目标平台风控，全都归因于节点。`,
`最后给出一个朴素结论：围绕“${a.keywords.split(',')[0]}”做选择时，透明度比峰值更重要。优先选择短周期、来源清楚的方案。`
];
function article(a){const paragraphs=expand(a);const sections=headings.map((h,i)=>`<section><h2>${h}</h2>${paragraphs.slice(i===0?0:i+1,i===4?9:i+3).map(x=>`<p>${x}</p>`).join('')}</section>`).join('');const related=topics.filter(x=>x.category===a.category&&x.slug!==a.slug).slice(0,3);const schema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.dek,datePublished:a.date,dateModified:a.date,author:{"@type":"Organization",name:site.author},publisher:{"@type":"Organization",name:site.name},mainEntityOfPage:url('/articles/'+a.slug+'.html'),keywords:a.keywords})}</script><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'首页',item:site.url},{"@type":"ListItem",position:2,name:'文章',item:url('/articles/')},{"@type":"ListItem",position:3,name:a.title,item:url('/articles/'+a.slug+'.html')}]})}</script>`;const body=`<div class="article-shell wrap"><article class="article"><div class="crumb"><a href="/index.html">首页</a> / <a href="/articles/index.html">文章</a> / ${categories[a.category].name}</div><header><span class="pill c-${a.category}">${categories[a.category].name}</span><h1>${a.title}</h1><p class="lead">${a.dek}</p><div class="byline"><span class="avatar">雷</span><span><b>${site.author}</b><small>更新于 ${a.date} · ${a.read} 分钟阅读</small></span></div></header><div class="takeaway"><b>先说结论</b><p>${a.points[0]}</p></div>${sections}<div class="notice"><b>合规与安全提醒</b><p>请遵守所在地法律法规、单位网络政策和第三方服务条款。本文只提供一般技术信息，不构成法律意见，也不提供节点或绕过授权的服务。</p></div></article><aside class="toc"><b>本文目录</b>${headings.map((h,i)=>`<a href="#s${i}">${i+1}. ${h}</a>`).join('')}<div class="aside-box">不确定从哪查？<a href="/faq.html">查看 FAQ →</a></div></aside></div><section class="related wrap"><h2>继续阅读</h2><div class="grid">${related.map(card).join('')}</div></section>`;let finalBody=body;headings.forEach((h,i)=>{finalBody=finalBody.replace(`<section><h2>${h}`,`<section id="s${i}"><h2>${h}`)});return layout({title:`${a.title}｜机场雷达`,desc:a.dek,pathName:`/articles/${a.slug}.html`,body:finalBody,schema,type:'article'})}
topics.forEach(a=>write(`articles/${a.slug}.html`,article(a)));
const all=`<section class="page-hero"><div class="wrap"><span>FIELD NOTES / ${topics.length}</span><h1>全部文章</h1><p>从第一次导入订阅，到看懂日志、测速与隐私边界。</p></div></section><section class="section wrap"><div class="filters">${Object.entries(categories).map(([k,v])=>`<button data-filter="${k}">${v.name}</button>`).join('')}<button data-filter="all" class="active">全部</button></div><div class="grid article-grid">${topics.map(card).join('')}</div></section><script>document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.article-grid .card').forEach(c=>c.hidden=b.dataset.filter!=='all'&&!c.querySelector('.c-'+b.dataset.filter))})</script>`;
write('articles/index.html',layout({title:'全部文章｜机场雷达',desc:'机场雷达全部 VPN、机场、小火箭、Clash、节点测速与隐私安全教程。',pathName:'/articles/',body:all}));
const faqSchema=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))})}</script>`;
write('faq.html',layout({title:'VPN 机场常见问题 FAQ｜机场雷达',desc:'关于 VPN 机场、小火箭、订阅、节点测速、隐私与多设备使用的常见问题。',pathName:'/faq.html',schema:faqSchema,body:`<section class="page-hero"><div class="wrap"><span>QUICK ANSWERS</span><h1>常见问题</h1><p>短答案先解决问题，复杂情况再去读完整指南。</p></div></section><section class="faq wrap">${faqs.map(([q,a],i)=>`<details ${i===0?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span>${q}<i>＋</i></summary><p>${a}</p></details>`).join('')}</section>`}));
write('about.html',layout({title:'关于机场雷达｜编辑原则与内容说明',desc:'了解机场雷达的编辑原则、内容边界与更新方式。',pathName:'/about.html',body:`<section class="page-hero"><div class="wrap"><span>ABOUT THE RADAR</span><h1>我们不替你做决定，<br>只把判断依据摆清楚。</h1></div></section><section class="prose wrap"><h2>为什么做这个站</h2><p>代理工具的中文资料不少，但许多文章不是过期截图，就是堆满无法验证的“最佳推荐”。机场雷达想做得更朴素：解释名词、记录排错顺序、说明隐私代价，并承认工具能力的边界。</p><h2>编辑原则</h2><p>不出售节点，不接受付费排名，不把一次测速写成长期结论。涉及软件版本与法规时标注日期；无法独立验证的商家宣传，不作为事实引用。教程优先给出可回退、可复现的步骤。</p><h2>内容边界</h2><p>本站提供一般网络与隐私教育内容，不提供绕过授权、攻击、欺诈或其他违法用途的操作指导。不同地区规则不同，读者应自行核对所在地法律和组织政策。</p><h2>勘误与更新</h2><p>网络工具变化很快。若页面步骤已经失效，请记录文章标题、设备系统、客户端版本和具体差异，方便编辑复核。我们宁愿删掉过期结论，也不靠旧流量撑页面。</p></section>`}));
for(const [key,cat] of Object.entries(categories)){const subset=topics.filter(a=>a.category===key);write(`topics/${key}.html`,layout({title:`${cat.name}教程与文章｜机场雷达`,desc:`机场雷达关于${cat.name}的实用教程与排错文章。`,pathName:`/topics/${key}.html`,body:`<section class="page-hero"><div class="wrap"><span>TOPIC / ${subset.length}</span><h1>${cat.name}</h1><p>经过整理的操作步骤、判断方法与风险提示。</p></div></section><section class="section wrap"><div class="grid">${subset.map(card).join('')}</div></section>`}))}
const recommendedSlugs=['airport-buying-checklist','node-selection','node-speed-test','free-vpn-risk','airport-running-risk','streaming-nodes','multi-device-setup','vpn-jichang-guide'];
const recommended=topics.filter(article=>recommendedSlugs.includes(article.slug));
const providers=[
  {rank:1,name:'闪电鼠',logo:'shandianshu.jpg',tag:'综合首选',code:'sd88',url:'https://chaore01.shandianshuaff.com/#/?code=HeUwm3zo',feature:'从轻量入门到 500GB 大流量档位都覆盖，价格梯度直观，适合希望一站式完成日常浏览、影音与多设备使用的读者。',fit:'适合第一次选择机场、重视套餐均衡度的人群',points:['60GB 年付小包适合轻量用户','120GB 至 500GB 月付档位清晰','输入专属码后统一按 7 折结算'],plans:[['限时钜惠小包','¥67.2/年','¥96/年','60GB/月'],['轻快版','¥15.4/月','¥22/月','120GB/月'],['疾速版','¥28/月','¥40/月','250GB/月'],['雷霆版','¥49/月','¥70/月','500GB/月']]},
  {rank:2,name:'大佬云',logo:'dalaoyun.png',tag:'套餐丰富',code:'dly88',url:'https://chaore01.dalaoyunaff.com/#/?code=rtH3pPer',feature:'月付、年付与一次性流量包同时提供，选择空间更大。轻量用户可以控制预算，大流量用户也能找到 600GB 档位。',fit:'适合希望灵活切换周期、需要一次性流量包的人群',points:['130GB 至 600GB 月付套餐','提供 78GB 与 160GB 一次性流量','不同使用周期更容易匹配预算'],plans:[['年付活动包','¥67.2/年','¥96/年','60GB/月'],['初云·入门版','¥16.1/月','¥23/月','130GB/月'],['凌云·基础版','¥30.1/月','¥43/月','300GB/月'],['御云·高级版','¥51.1/月','¥73/月','600GB/月'],['闲云·随心包','¥69.3/一次','¥99/一次','78GB 总量'],['悠云·长享包','¥139.3/一次','¥199/一次','160GB 总量']]},
  {rank:3,name:'神行加速',logo:'shenxing.png',tag:'流量进阶',code:'sx0077',url:'https://chaore01.shenxingaff.com/#/?code=iTjS2mVY',feature:'套餐从 130GB 平稳提升到 520GB，档位数量不复杂，适合不想在大量套餐中反复比较、希望快速作出决定的用户。',fit:'适合影音、下载及中高流量使用需求',points:['130GB 入门档降低选择门槛','260GB 与 520GB 适合持续使用','年付特惠版兼顾轻量需求'],plans:[['神行·尝鲜包','¥16.1/月','¥23/月','130GB/月'],['神行·基础包','¥28/月','¥40/月','260GB/月'],['神行·尊享包','¥50.4/月','¥72/月','520GB/月'],['神行·年付特惠版','¥67.2/年','¥96/年','60GB/月']]},
  {rank:4,name:'云界线',logo:'yunjiexian.png',tag:'弹性搭配',code:'yjx888',url:'https://chaore01.yunjiexianaff.com/#/?code=g2PDAa91',feature:'既有 150GB、300GB、600GB 月付套餐，也有不按月重置的一次性流量包，适合流量使用不稳定或需要备用方案的人群。',fit:'适合用量波动明显、希望保留备用流量的人群',points:['150GB 起步的月付选择','最高 600GB 月流量档位','80GB 与 200GB 一次性流量包'],plans:[['云界年付小包','¥67.2/年','¥96/年','60GB/月'],['轻云·基础版','¥15.4/月','¥22/月','150GB/月'],['凌云·进阶版','¥28/月','¥40/月','300GB/月'],['御云·高级版','¥46.2/月','¥66/月','600GB/月'],['闲云·随心包','¥69.3/一次','¥99/一次','80GB 总量'],['悠云·长享包','¥139.3/一次','¥199/一次','200GB 总量']]},
  {rank:5,name:'榴莲云',logo:'liulianyun.png',tag:'大流量优选',code:'ll88',url:'https://chaore01.liulianyunaff.com/#/?code=MNqUefcg',feature:'月付套餐以流量递增为主，从 140GB 到 750GB 覆盖明显，适合视频观看、远程协作和多台设备同时在线的场景。',fit:'适合高频影音、多设备及大流量用户',points:['140GB 至 750GB 多档月流量','高流量套餐价格跨度清楚','年付小包适合轻量备用'],plans:[['榴莲年付特惠版','¥67.2/年','¥96/年','60GB/月'],['轻享包','¥16.8/月','¥24/月','140GB/月'],['畅享包','¥28/月','¥40/月','260GB/月'],['尊享包','¥42/月','¥60/月','420GB/月'],['榴莲王','¥70/月','¥100/月','750GB/月']]},
  {rank:6,name:'环球梯',logo:'huanqiuti.jpg',tag:'场景覆盖',code:'HQ66',url:'https://chaore01.huanqiutiaff.com/#/?code=vXn9xcb8',feature:'同时覆盖学生轻量档、常规月付档和一次性流量包，适合按场景挑选，不必为了偶尔使用直接购买过大的长期套餐。',fit:'适合学生、轻量使用与临时大流量需求',points:['120GB 至 600GB 常规月付','80GB 与 400GB 一次性流量','不同预算都能找到对应档位'],plans:[['环球学生餐','¥67.2/年','¥96/年','60GB/月'],['环球轻享','¥15.4/月','¥22/月','120GB/月'],['环球畅游','¥27.3/月','¥39/月','240GB/月'],['环球尊享','¥48.3/月','¥69/月','600GB/月'],['环球随行包','¥69.3/一次','¥99/一次','80GB 总量'],['环球灵活包','¥209.3/一次','¥299/一次','400GB 总量']]}
];
const providerCards=providers.map(p=>`<article class="provider-card rank-${p.rank}" id="provider-${p.rank}"><header><div class="provider-rank"><small>推荐排名</small><b>${String(p.rank).padStart(2,'0')}</b></div><div class="provider-logo"><img src="/assets/recommendations/${p.logo}" alt="${p.name} Logo" loading="lazy" width="240" height="240"></div><div class="provider-name"><span class="provider-tag tag-${p.rank}">${p.tag}</span><h2>${p.name}</h2><p>${p.feature}</p><div class="provider-fit">适合人群：${p.fit}</div></div><div class="provider-coupon"><small>专属 7 折码</small><b>${p.code}</b><div class="provider-actions"><a class="register-link" href="${p.url}" target="_blank" rel="noopener noreferrer nofollow sponsored">立即注册 →</a><a class="deal-link" href="/deals.html#${p.name}">优惠说明</a></div></div></header><div class="provider-points">${p.points.map(x=>`<span>✓ ${x}</span>`).join('')}</div><div class="plan-list">${p.plans.map(([name,price,original,traffic])=>`<div class="plan-row"><b>${name}</b><div class="discount-price"><strong>${price}</strong><del>${original}</del></div><span>${traffic}</span></div>`).join('')}</div></article>`).join('');
const extraProviders=[
  {rank:7,name:'Flybit',logo:'/assets/recommendations/legacy/flybit.svg',tag:'老牌服务',url:'https://www.fastfastfast.buzz/#/register?code=tuAiVVbP',desc:'运营时间较长的服务之一。套餐价格、可用流量、节点覆盖与活动规则请进入官网后实时核对。'},
  {rank:8,name:'XSUS',logo:'/assets/recommendations/legacy/xsus.svg',tag:'老牌服务',url:'https://xsus.cloud/register?code=StNymuEe',desc:'长期运营的服务品牌。建议注册后先查看短周期方案、设备限制与退款说明。'},
  {rank:9,name:'网际快车',logo:'/assets/recommendations/legacy/wangjikuwaiche.svg',tag:'老牌服务',url:'https://johhhu.xn--66tw07h.com',desc:'老牌服务选择之一。购买前请核对套餐周期、流量倍率和实际结算价格。'},
  {rank:10,name:'大哥云',logo:'/assets/recommendations/legacy/dageyun.svg',tag:'老牌服务',url:'https://aff01.zygbx.com/#/register?code=vjFaxWEI',desc:'运营时间较长的服务品牌。具体线路、套餐和优惠信息以注册页面当前展示为准。'}
];
const extraProviderCards=extraProviders.map(p=>`<article class="extra-provider-card" id="provider-${p.rank}"><div class="extra-rank"><small>推荐排名</small><b>${String(p.rank).padStart(2,'0')}</b></div><div class="extra-mark"><img src="${p.logo}" alt="${p.name} Logo" loading="lazy" width="96" height="96" referrerpolicy="no-referrer"></div><div class="extra-provider-copy"><span>${p.tag}</span><h2>${p.name}</h2><p>${p.desc}</p></div><a href="${p.url}" target="_blank" rel="noopener noreferrer nofollow sponsored">前往官网注册 →</a></article>`).join('');
write('topics/recommend.html',layout({title:'机场推荐与套餐价格｜机场雷达',desc:'机场雷达推荐榜：闪电鼠、大佬云、神行加速、云界线、榴莲云、环球梯、Flybit、XSUS、网际快车和大哥云。',pathName:'/topics/recommend.html',body:`<section class="page-hero recommend-hero"><div class="wrap"><span>RECOMMENDED SERVICES / 10</span><h1>机场推荐</h1><p>按照本站当前推荐顺序展示十家服务；已获得后台资料的服务同步整理套餐价格与流量信息。</p><div class="recommend-date">资料整理：2026-09-30 · 价格、流量与活动可能调整，最终以商家结算页面为准。</div></div></section><section class="recommend-intro"><div class="wrap"><div><b>阅读说明</b><h2>先看使用需求，再看套餐价格。</h2></div><div class="recommend-points"><p><strong>01</strong> 前六家已整理套餐与七折码，新增四家暂时仅提供注册入口。</p><p><strong>02</strong> 月付流量与一次性流量不能直接比较，请注意套餐周期。</p><p><strong>03</strong> 建议先短周期体验，并在付款前核对倍率、设备限制和退款规则。</p></div></div></section><section class="provider-section wrap"><div class="provider-heading"><span>CURRENT RANKING</span><h2>十家推荐机场与套餐</h2><p>前六家展示套餐与专属优惠；新增四家暂未收到套餐资料，因此不虚构价格和折扣。</p></div><div class="provider-list">${providerCards}</div><div class="extra-provider-heading"><span>MORE OPTIONS</span><h2>新增推荐入口</h2><p>以下服务目前仅展示注册入口，套餐信息以各自官网为准。</p></div><div class="extra-provider-list">${extraProviderCards}</div></section><section class="section wrap"><div class="section-head"><div><span>SELECTION NOTES</span><h2>选择机场前先读这些</h2></div></div><div class="grid">${recommended.map(card).join('')}</div></section>`}));
write('alerts.html',layout({title:'机场跑路预警与风险信号｜机场雷达',desc:'基于第三方公开状态库整理的机场服务历史异常记录，并提供来源、日期与风险提示。',pathName:'/alerts.html',body:alertsBodyV2}));
write('deals.html',layout({title:'机场优惠码与优惠活动｜机场雷达',desc:'收录经过官方来源核验、标明有效期和适用范围的机场优惠信息。',pathName:'/deals.html',body:dealsBody}));
write('resources.html',layout({title:'代理工具与网络安全资源栏｜机场雷达',desc:'Shadowrocket、Clash Verge Rev 官方下载以及网络测速、浏览器隐私检查资源。',pathName:'/resources.html',body:resourcesBody}));
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
write('CNAME','jcleida.com\n');
const paths=['/','/articles/','/faq.html','/about.html','/alerts.html','/deals.html','/resources.html','/topics/recommend.html',...Object.keys(categories).map(k=>`/topics/${k}.html`),...topics.map(a=>`/articles/${a.slug}.html`)];
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${paths.map(p=>`  <url>\n    <loc>${url(p)}</loc>\n    <lastmod>2026-09-30</lastmod>\n  </url>`).join('\n')}\n</urlset>\n`);
write('rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${site.name}</title><link>${site.url}</link><description>${site.description}</description>${topics.slice(0,15).map(a=>`<item><title>${esc(a.title)}</title><link>${url('/articles/'+a.slug+'.html')}</link><guid>${url('/articles/'+a.slug+'.html')}</guid><pubDate>${new Date(a.date+'T08:00:00+08:00').toUTCString()}</pubDate><description>${esc(a.dek)}</description></item>`).join('')}</channel></rss>`);
console.log(`Built ${paths.length} pages in ${out}`);
if(process.argv.includes('--serve')){http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=path.join(out,p);if(!f.startsWith(out)||!fs.existsSync(f)){res.writeHead(404);return res.end('404')}res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.css')?'text/css':'application/xml');fs.createReadStream(f).pipe(res)}).listen(4173,()=>console.log('http://localhost:4173'))}
